<?php
// Doing it this way might break when we do eventually change the JSON Structure. -K9
$base = array( 'Version' => NULL, 
                'Meta' => array ( 
                    'ElapsedTime' => NULL, 
                    'GenerationDate' => NULL, 
                    ), 
                'BasicInfo' => array ( 
                    'Edition' => NULL, 
                    'Version' => NULL, 
                    'FriendlyVersion' => NULL, 
                    'InstallDate' => NULL, 
                    'Uptime' => NULL, 
                    'Hostname' => NULL, 
                    'Username' => NULL, 
                    'Domain' => NULL, 
                    'BootMode' => NULL, 
                    'BootState' => NULL, 
                ), 
                'System' => array ( 
                    'UserVariables' => NULL, 
                    'SystemVariables' => NULL, 
                    'RunningProcesses' => NULL, 
                    'Services' => NULL, 
                    'InstalledApps' => NULL, 
                    'InstalledHotfixes' => NULL, 
                    'ScheduledTasks' => NULL, 
                    'WinScheduledTasks' => NULL, 
                    'StartupTasks' => NULL, 
                    'PowerProfiles' => NULL, 
                    'MicroCodes' => NULL, 
                    'RecentMinidumps' => NULL, 
                    'DumpZip' => NULL, 
                    'StaticCoreCount' => NULL, 
                    'ChoiceRegistryValues' => NULL, 
                    'UsernameSpecialCharacters' => NULL, 
                    'OneDriveCommercialPathLength' => NULL, 
                    'OneDriveCommercialNameLength' => NULL, 
                    'BrowserExtensions' => NULL, 
                    'DefaultBrowser' => NULL, 
                    'PageFile' => NULL, 
                ), 
                'Hardware' => array ( 
                    'Ram' => NULL, 
                    'Cpu' => NULL, 
                    'Gpu' => NULL, 
                    'Motherboard' => NULL, 
                    'AudioDevices' => NULL, 
                    'Monitors' => NULL, 
                    'Drivers' => NULL, 
                    'Devices' => NULL, 
                    'BiosInfo' => NULL, 
                    'Storage' => NULL, 
                    'Temperatures' => NULL, 
                    'Batteries' => NULL, 
                ), 
                'Security' => array ( 
                    'AvList' => NULL, 
                    'FwList' => NULL, 
                    'UacEnabled' => NULL, 
                    'SecureBootEnabled' => NULL, 
                    'UacLevel' => NULL, 
                    'Tpm' => NULL, 
                ), 

                'Network' => array ( 
                    'Adapters' => NULL, 
                    'Adapters2' => NULL, 
                    'Routes' => NULL, 
                    'NetworkConnections' => NULL, 
                    'HostsFile' => NULL, 
                    'HostsFileHash' => NULL, 
                ), 
                'Issues' => NULL, 
                'DebugLogText' => NULL
            );
?>
