<?php
/*
 * Various lists that are used in the viewers
 */

$puplist = [
    "100bao",
    "1DE1",
    "485E",
    "4shared",
    "51.com",
    "64CB",
    "8ECAA",
    "8x8",
    "accellion",
    "activesync",
    "adobe-connect",
    "adobe-connectnow",
    "adrive",
    "Advanced SystemCare",
    "afreeca",
    "aim-express",
    "aim-mail",
    "aim",
    "aim",
    "all-slots-casino",
    "allpeers",
    "amazon-cloud-drive",
    "amazon-unbox",
    "ameba-now",
    "ants-p2p",
    "aol-proxy",
    "appcelerator",
    "apple-appstore",
    "applejuice",
    "ares",
    "asf-streaming",
    "asproxy",
    "atom",
    "att-connect",
    "Avast",
    "avaya-webalive",
    "AVG",
    "avoidr",
    "aws-workdocs",
    "axifile",
    "azureus",
    "babelgum",
    "badongo",
    "baidu-hi",
    "baofeng",
    "base-crm",
    "bebo",
    "bigupload",
    "bitcoin",
    "bittorrent-sync",
    "bittorrent",
    "blackberry",
    "blog-posting",
    "boldchat-logmein",
    "bomgar",
    "bonpoo",
    "boxnet",
    "brightcove",
    "Browser Assistant",
    "bypass",
    "bypassthat",
    "caihong",
    "camfrog",
    "camo-proxy",
    "canvas",
    "carbonite",
    "ccleaner",
    "cFosSpeed",
    "cgi-irc",
    "cgiproxy",
    "circumventor",
    "Citrix",
    "Cleaner",
    "clip2net",
    "cloudshare",
    "Clownfish Voice Changer",
    "coinhave",
    "coinhive",
    "coinimp",
    "coinnebula",
    "concur",
    "coralcdn-user",
    "crossloop",
    "crypto-loot",
    "cyworld",
    "daap",
    "dailymotion",
    "datto-backupify",
    "daum-touch",
    "daum",
    "deepminer",
    "dialpad",
    "diino",
    "direct-connect",
    "divshare",
    "dl-free",
    "docstoc",
    "dontcensorme",
    "dostupest",
    "drivehq",
    "Driver Booster",
    "Driver Easy",
    "DriverFix",
    "droidvpn",
    "drop.io",
    "dropboks",
    "dropbox",
    "e-signlive",
    "easy-share",
    "eatlime",
    "ebuddy",
    "editgrid",
    "egnyte",
    "elluminate",
    "emule",
    "eroom-net",
    "eventbrite",
    "expand 51.com-webdisk",
    "expand adobe-connectnow-file-transfer",
    "expand adobe-meeting-file-transfer",
    "expand aim-audio",
    "expand aim-base",
    "expand aim-express-base",
    "expand aim-file-transfer",
    "expand amazon-cloud-drive-base",
    "expand amazon-cloud-drive-uploading",
    "expand ameba-now-base",
    "expand ameba-now-posting",
    "expand avaya-webalive-file-transfer",
    "expand baidu-hi-file-transfer",
    "expand bebo-posting",
    "expand boxnet-uploading",
    "expand carbonite-downloading",
    "expand carbonite-uploading",
    "expand concur-base",
    "expand daum-cloud",
    "expand daum-mail",
    "expand docstoc-base",
    "expand docstoc-uploading",
    "expand dropbox-base",
    "expand egnyte-base",
    "expand facebook-apps",
    "expand facebook-base",
    "expand facebook-file-sharing",
    "expand facebook-posting",
    "expand facebook-video",
    "expand filestack-downloading",
    "expand fuze-meeting-file-sharing",
    "expand genesys-base",
    "expand gmail-base",
    "expand gmail-enterprise",
    "expand google-hangouts-chat",
    "expand google-talk-base",
    "expand gtalk-file-transfer",
    "expand gtalk-voice",
    "expand hdfs",
    "expand imgur-base",
    "expand instan-t-file-transfer",
    "expand irc-base",
    "expand irc-dcc-file-transfer",
    "expand issuu-uploading",
    "expand join-me-file-transfer",
    "expand live-mesh-base",
    "expand live-mesh-sync",
    "expand lotus-notes-base",
    "expand lotuslive-file-sharing",
    "expand lotuslive-meeting-file-sharing",
    "expand mail.ru-agent-file-transfer",
    "expand mail.ru-base",
    "expand meebo-file-transfer",
    "expand mendeley-base",
    "expand mendeley-uploading",
    "expand mercurial-base",
    "expand mixi-posting",
    "expand ms-onedrive-base",
    "expand ms-onedrive-downloading",
    "expand msn-base",
    "expand msn-file-transfer",
    "expand msn-voice",
    "expand myspace-base",
    "expand myspace-mail",
    "expand myspace-posting",
    "expand nateon-file-transfer",
    "expand nateon-im-base",
    "expand noteworthy-base",
    "expand odnoklassniki-base",
    "expand pastebin-base",
    "expand pinterest-posting",
    "expand qq-base",
    "expand qq-file-transfer",
    "expand reddit-posting",
    "expand rediffbol-file-transfer",
    "expand screencast-base",
    "expand scribd-uploading",
    "expand second-life-base",
    "expand sharefile-base",
    "expand sharefile-downloading",
    "expand sharefile-uploading",
    "expand sina-uc-web-disk",
    "expand sina-weibo-base",
    "expand skydrive-base",
    "expand skydrive-uploading",
    "expand smtp-base",
    "expand smtp-starttls",
    "expand teamup-calendar-base",
    "expand teamup-calendar-uploading",
    "expand thwapr-uploading",
    "expand twitter-messaging",
    "expand twitter-posting",
    "expand twitter-uploading",
    "expand vimeo-base",
    "expand vkontakte-base",
    "expand vkontakte-mail",
    "expand vnc-base",
    "expand yahoo-file-transfer",
    "expand yahoo-im-base",
    "expand yahoo-voice",
    "expand youku-base",
    "expand yousendit-base",
    "expand yousendit-uploading",
    "expand youtube-base",
    "expand youtube-safety-mode",
    "expand youtube-streaming",
    "expand youtube-uploading",
    "expand yunpan360-base",
    "F0C7",
    "facebook",
    "fastmail",
    "fasttrack",
    "feidian",
    "fetch.io",
    "file-host",
    "filecatalyst-direct",
    "filedropper",
    "fileguri",
    "filemail",
    "filer.cx",
    "fileserve",
    "filesonic",
    "filestack",
    "fileswire",
    "firephoenix",
    "flash",
    "flashget",
    "flock",
    "fluxiom",
    "fly-proxy",
    "foldera",
    "foxy",
    "freedome",
    "freegate",
    "freenet",
    "friendvox",
    "frozenway",
    "fs2you",
    "ftp",
    "fufox",
    "funshion",
    "fuze-meeting",
    "g.ho.st",
    "gadu-gadu",
    "GamePlayLabs",
    "gbridge",
    "generic-p2p",
    "genesys",
    "ghostsurf",
    "gizmo",
    "glide",
    "glype-proxy",
    "gmail",
    "gmx-mail",
    "gnu-httptunnel",
    "gnunet",
    "gnutella",
    "goagent",
    "goboogy",
    "gogobox",
    "google-base",
    "google-buzz",
    "google-chat",
    "google-desktop",
    "google-drive-web",
    "google-hangouts",
    "google-talk",
    "google-talk",
    "gpass-proxy",
    "gpass",
    "graboid-video",
    "gtunnel",
    "guardster",
    "gyao",
    "h.323",
    "hadoop",
    "hamachi",
    "hangame",
    "hola-unblocker",
    "homepipe",
    "hopster",
    "horde",
    "hotfile",
    "hotline",
    "hotmail",
    "http-audio",
    "http-nsri",
    "http-proxy",
    "http-tunnel",
    "http-video",
    "httport",
    "I Want This",
    "i2p",
    "icmp",
    "icmpsh",
    "icq",
    "ifile.it",
    "ifolder",
    "ilohamail",
    "im-plus",
    "imap",
    "imesh",
    "imgur",
    "imhaha",
    "imo",
    "instan-t",
    "ip-in-ip",
    "ipfs",
    "irc",
    "issuu",
    "iTop",
    "jabber",
    "jap",
    "join-me",
    "jsecoin",
    "jubii",
    "justin.tv",
    "jxta",
    "Kaspersky",
    "kazaa",
    "kerio-vpn",
    "kino",
    "KMS",
    "korea-webmail",
    "kproxy",
    "kugoo",
    "labnol-proxy",
    "laconica",
    "leapfile",
    "libero-video",
    "limelight",
    "live-meeting",
    "live-mesh",
    "logmein",
    "lotus-notes",
    "lotus-sametime",
    "lotuslive",
    "mail.com",
    "mail.ru-agent",
    "mail.ru",
    "mailchimp",
    "Malwarebytes",
    "manolito",
    "McAfee",
    "me2day",
    "mediafire",
    "meebo",
    "megashare",
    "megashares",
    "megaupload",
    "mendeley",
    "mercurial",
    "metacafe",
    "mgoon",
    "mibbit",
    "Microsoft Office Enterprise 2007",
    "mineralt",
    "mixi",
    "mobile-me",
    "mogulus",
    "monect",
    "monectserver",
    "ms-exchange",
    "ms-groove",
    "ms-onedrive",
    "ms-rdp",
    "ms-update",
    "msn",
    "msn",
    "msn2go",
    "mute",
    "MyCleanPC",
    "mydownloader",
    "myspace",
    "MyWebSearch.J",
    "nakido-flag",
    "nate-video",
    "nateon-im",
    "naver-ndrive",
    "ndmp",
    "neonet",
    "nerohut",
    "netease-mail",
    "netload",
    "netlog",
    "netmeeting",
    "niconico-douga",
    "nintendo-wfc",
    "nntp",
    "Norton",
    "noteworthy",
    "Ocl",
    "octopz",
    "odnoklassniki",
    "office-live",
    "okurin",
    "omnidrive",
    "opendoor",
    "openft",
    "openmeetings",
    "openomy",
    "opera-mini",
    "oridus-nettouch",
    "orkut",
    "orsiso",
    "outblaze-mail",
    "outlook-web",
    "p10",
    "packetix-vpn",
    "pando",
    "pandora-tv",
    "party-poker",
    "pastebin",
    "peerenabler",
    "perfect-dark",
    "phproxy",
    "pichat",
    "ping-tunnel",
    "pingfu",
    "pinterest",
    "plaxo",
    "poco",
    "poker-stars",
    "pop3",
    "pownce",
    "pplive",
    "ppstream",
    "pptp",
    "privax",
    "proxeasy",
    "proxono",
    "psiphon",
    "puffin",
    "putlocker",
    "qdown",
    "qq-download",
    "qq-mail",
    "qq",
    "qq",
    "qqlive",
    "qvod",
    "r-exec",
    "r-services",
    "radmin",
    "rapidshare",
    "rdp2tcp",
    "reddit",
    "rediffbol",
    "reduh",
    "Reimage Repair",
    "remobo",
    "remote",
    "remoteview",
    "ringcentral",
    "rlogin",
    "Roblox",
    "roundcube",
    "rsh",
    "rtmp",
    "rtmpe",
    "rtmpt",
    "ruckus",
    "saba-centra-meeting",
    "salad",
    "scotty",
    "screencast",
    "screenconnect",
    "scribd",
    "seamless-phenom",
    "second-life",
    "secret",
    "secure-access",
    "secureserver-mail",
    "security-kiss",
    "sendspace",
    "share-p2p",
    "sharebase.to",
    "sharebox",
    "sharefile",
    "showmypc",
    "silent-circle",
    "simplehelp",
    "simplite-msn",
    "sina-uc",
    "sina-weibo",
    "sip",
    "sipviaheader-nat",
    "sky-player",
    "skydrive",
    "sliderocket",
    "smtp",
    "smtp",
    "socialtv",
    "socks",
    "socks2http",
    "sopcast",
    "soribada",
    "sosbackup",
    "soulseek",
    "source-engine",
    "spark",
    "Speedify",
    "spotnet",
    "sproutsocial",
    "squirrelmail",
    "ssh-tunnel",
    "ssh",
    "ssl",
    "stealthnet",
    "steganos-vpn",
    "stickam",
    "storage.to",
    "stumbleupon",
    "sugarsync",
    "suresome",
    "surrogafier",
    "swapper",
    "synology-cloudstation",
    "synology-dsm",
    "System Mechanic",
    "tagoo",
    "taku-file-bin",
    "tcp-over-dns",
    "teamup-calendar",
    "techinline",
    "telenet-webmail",
    "tesla",
    "tftp",
    "thecircle",
    "thinkfree",
    "thwapr",
    "timbuktu",
    "tor2web",
    "totodisk",
    "totoexpress",
    "transferbigfiles",
    "trinoo",
    "Trojan.Win32.Generic!BT",
    "TronScript",
    "tubes",
    "tudou-speedup",
    "tudou",
    "tunnelbear",
    "turboshare",
    "turboupload",
    "tvants",
    "twig",
    "twitch",
    "twitter",
    "txp",
    "ultrasurf",
    "UltraUXThemePatcher",
    "uploading",
    "usejump",
    "usermin",
    "uusee",
    "vagaa",
    "veetle",
    "vimeo",
    "vkontakte",
    "vnc-http",
    "vnc",
    "vnn",
    "Voicemeeter",
    "Voicemod",
    "Voxal Voice Changer",
    "vsee",
    "vtun",
    "vtunnel",
    "vyew",
    "Wallpaper Engine",
    "warez-p2p",
    "web-browsing",
    "web-crawler",
    "web-de-mail",
    "webaim",
    "webdav",
    "webhard",
    "webmine",
    "webot",
    "webqq",
    "wickr",
    "winmx",
    "winny",
    "woofiles",
    "x11",
    "xdrive",
    "xunlei",
    "yahoo-douga",
    "yahoo-im",
    "yandex-mail",
    "yoics",
    "yoomba",
    "youku",
    "your-freedom",
    "yourfilehost",
    "yousendit",
    "youtube",
    "yunpan360",
    "zamzar",
    "zango",
    "zbigz",
    "zelune",
    "zenbe",
    "zoho-im"
];

$biosCharacteristics = [
    3 => "BIOS Characteristics are not supported.",
    4 => "ISA is supported.",
    5 => "MCA is supported.",
    6 => "EISA is supported.",
    7 => "PCI is supported.",
    8 => "PC card (PCMCIA) is supported.",
    9 => "Plug and Play is supported.",
    10 => "APM is supported.",
    11 => "BIOS is upgradeable (Flash).",
    12 => "BIOS shadowing is allowed.",
    13 => "VL-VESA is supported.",
    14 => "ESCD support is available.",
    15 => "Boot from CD is supported.",
    16 => "Selectable boot is supported.",
    17 => "BIOS ROM is socketed.",
    18 => "Boot from PC card (PCMCIA) is supported.",
    19 => "EDD specification is supported.",
    20 => "Japanese floppy for NEC 9800 1.2 MB (3.5”, 1K bytes/sector, 360 RPM) is supported.",
    21 => "Japanese floppy for Toshiba 1.2 MB (3.5”, 360 RPM) is supported.",
    22 => "5.25” / 360 KB floppy services are supported.",
    23 => "5.25” /1.2 MB floppy services are supported.",
    24 => "3.5” / 720 KB floppy services are supported.",
    25 => "3.5” / 2.88 MB floppy services are supported.",
    26 => "Print screen Service is supported.",
    27 => "8042 keyboard services are supported.",
    28 => "Serial services are supported.",
    29 => "Printer services are supported.",
    30 => "CGA/Mono Video Services are supported.",
    31 => "NEC PC-98."
];

$defaultRegKeys = [
    "TdrLevel" => [3],
    "NonBestEffortLimit" => [20],
    "NetworkThrottlingIndex" => [10],
    "EnableSuperfetch" => [null],
    "DisableAntiVirus" => [0],
    "DisableAntiSpyware" => [0],
    "PUAProtection" => [0],
    "PassiveMode" => [0],
    "DontReportInfectionInformation" => [1],
    "Disabled" => [0],
    "AllowUpgradesWithUnsupportedTPMOrCPU" => [null],
    "HwSchMode" => [1],
    "UseWUServer" => [1],
    "NoAutoUpdate" => [0],
    "HiberbootEnabled" => [1],    // side note, probably should be disabled cause bugs but eh its default
    "AuditBoot" => [1],
    "AllowBuildPreview" => [2],
    "BypassCPUCheck" => [null],
    "BypassStorageCheck" => [null],
    "BypassRAMCheck" => [null],
    "BypassTPMCheck" => [null],
    "BypassSecureBootCheck" => [null],
    "SV2" => [null],
    "Win32PrioritySeparation" => [2],
    "Windows Error Reporting\\Disabled" => [null],
    "Windows Defender\\Passive Mode" => [null],
    "UnsupportedHardwareNotificationCache\\SV2" => [null]
];
